"""Modelo canônico da nota fiscal e os metadados da extração."""

from nfscan.modelo.extracao import ArquivoOrigem, CampoExtraido, Extracao, Problema
from nfscan.modelo.nota import (
    Documento,
    Endereco,
    Finalidade,
    FormaPagamento,
    ImpostoItem,
    Impostos,
    Item,
    ModalidadeFrete,
    NotaFiscal,
    Pagamento,
    Parcela,
    Participante,
    RegimeTributario,
    Retencoes,
    Situacao,
    TipoDocumento,
    TipoPagamento,
    Totais,
    Transporte,
    Tributos,
    Volume,
)
from nfscan.modelo.tipos import VERSAO_SCHEMA, Dinheiro, Quantidade

__all__ = [
    "VERSAO_SCHEMA",
    "ArquivoOrigem",
    "CampoExtraido",
    "Dinheiro",
    "Documento",
    "Endereco",
    "Extracao",
    "Finalidade",
    "FormaPagamento",
    "ImpostoItem",
    "Impostos",
    "Item",
    "ModalidadeFrete",
    "NotaFiscal",
    "Pagamento",
    "Parcela",
    "Participante",
    "Problema",
    "Quantidade",
    "RegimeTributario",
    "Retencoes",
    "Situacao",
    "TipoDocumento",
    "TipoPagamento",
    "Totais",
    "Transporte",
    "Tributos",
    "Volume",
]
